### ISSUE TITLE
Forking processes doesn't work quite well

### ISSUE THREAD

**Issue by jeroenh** [ddos-clearing-house/ddos_dissector#3]
When I run from the command line I get error messages about Forking. When I run everything manually from the interpreter, everything works fine.

Compare:
```
$ python ddos_dissector.py --input input4test/1.pcap
input file: /var/folders/jr/dzm6587x09s5v2d3mm4898b40000gp/T/tmp7rj671p0
output file: output/d0ccb10c7e08ac2d4a16804d53b30845.pcap
1375 packets (523467 bytes) written
objc[34625]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[34625]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
^CProcess ForkPoolWorker-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/queues.py", line 335, in get
    res = self._reader.recv_bytes()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Traceback (most recent call last):
  File "ddos_dissector.py", line 80, in <module>
    ddos_dissector(input_file)
  File "ddos_dissector.py", line 54, in ddos_dissector
    p.starmap(anonymize, items)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 638, in get
    self.wait(timeout)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 635, in wait
    self._event.wait(timeout)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
```

```
$ python
Python 3.6.5 (default, Apr 16 2018, 09:16:50)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import functions.attack_vector_anonymizer
>>> import functions.dataframe_analysis
>>> import functions.file_type_parser
>>> functions.file_type_parser.determine_file_type("input4test/1.pcap")
'pcap'
>>> df = functions.file_type_parser.convert_to_dataframe("input4test/1.pcap","pcap")
>>> functions.dataframe_analysis.analyze_dataframe(df,"pcap")

DISTRIBUTION OF DESTINATION IPS:
[...]

```

**Comment by Koenvh1** [comment]
It might be caused by an issue that was introduced in macOS High Sierra when it comes to multiprocessing, as I cannot reproduce the issue (on Linux). To circumvent that issue, I created this workaround (https://github.com/jjsantanna/ddosdb/commit/dcbf1aa9d1045e657afc5e9e4992bd15b941f24d). 

Could you test if it works with that fix (which can be found on the [maintainability-improvements](https://github.com/jjsantanna/ddosdb/tree/maintainability-improvements) branch)?

**Comment by jeroenh** [comment]
That works, but then you're only using threads, not processes.

I found that this workaround also works: https://blog.yimingliu.com/2015/07/22/python-multiprocessing-code-crashes-on-os-x-under-ipython/

This seems referenced here: https://bugs.python.org/issue31818

**Comment by Koenvh1** [comment]
Correct, though given that the largest bottleneck occurs while generated the attack vector, which is an external process anyway, it should only minimally affect performance.
