### ISSUE TITLE
exception not handled 

### ISSUE THREAD

**Issue by joaoceron** [ddos-clearing-house/ddos_dissector#36]
INFO - Reprocessing attack based on protocols: ['ARP', 'BROWSER', 'CDP', 'DB-LSP-DISC', 'HTTP', 'ICMP', 'SSH', 'STP', 'TCP', 'UDP']
Traceback (most recent call last):
  File "./ddos_dissector.py", line 1429, in <module>
    (fingerprint,json_file) = prepare_fingerprint_upload(df_fingerprint,df,fingerprint,n_type,labels)
  File "./ddos_dissector.py", line 1266, in prepare_fingerprint_upload
    initial_timestamp = datetime.utcfromtimestamp(initial_timestamp).strftime('%Y-%m-%d %H:%M:%S')
ValueError: Invalid value NaN (not a number)

**Comment by joaoceron** [comment]
fixed
